### ISSUE TITLE
CEL - Layer 2 WG Roadmap

### ISSUE THREAD

**Issue by misilva73** [protocol/CryptoEconLab#24]
eta: 2023-03-31
children:
- [x] https://github.com/protocol/CryptoEconLab/issues/22
- [x] https://github.com/protocol/cel-retrieval/issues/26
- [x] https://github.com/protocol/cel-retrieval/issues/11
- [ ] https://github.com/protocol/CryptoEconLab/issues/21
- [x] https://github.com/protocol/cel-retrieval/issues/19
- [ ] https://github.com/protocol/CryptoEconLab/issues/23
- [x] https://github.com/protocol/cel-retrieval/issues/22
